# Generated by Django 6.0.5 on 2026-05-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_person_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
