# Generated by Django 6.0.5 on 2026-05-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_person_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='apellidos',
            new_name='apellido_paterno',
        ),
        migrations.AddField(
            model_name='person',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='role',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=1, help_text='Nivel de jerarquía (a mayor número, mayor autoridad)'),
        ),
    ]
