# Generated by Django 6.0.5 on 2026-05-25 14:52

import django.db.models.deletion
from django.db import migrations, models

def crear_niveles_iniciales(apps, schema_editor):
    # Usamos el registro de la migración para obtener el modelo Nivel
    Nivel = apps.get_model('accounts', 'Nivel')
    
    # 1. Creamos el nivel con ID 1 (usamos update_or_create por seguridad)
    Nivel.objects.update_or_create(
        id=1,
        defaults={'nombre': 'Administrador', 'valor': 100}
    )
    
    # 2. Creamos los demás niveles con IDs fijos para evitar colisiones con la secuencia
    Nivel.objects.update_or_create(id=2, defaults={'nombre': 'Verificador', 'valor': 50})
    Nivel.objects.update_or_create(id=3, defaults={'nombre': 'Usuario', 'valor': 10})

    # 3. Sincronizar la secuencia de PostgreSQL para evitar el error de "llave duplicada"
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT setval(pg_get_serial_sequence('niveles', 'id'), coalesce(max(id), 1)) FROM niveles;")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_apellidos_person_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('valor', models.PositiveSmallIntegerField(help_text='Valor numérico de la jerarquía (a mayor número, mayor autoridad)', unique=True)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'db_table': 'niveles',
            },
        ),
        migrations.RunPython(crear_niveles_iniciales),
        migrations.AlterField(
            model_name='role',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='accounts.nivel'),
        ),
    ]
