# Generated by Django 6.0.5 on 2026-05-25 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_departamento_remove_person_role_person_superior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_dependientes', to='accounts.cargo'),
        ),
    ]
