# Generated by Django 6.0.5 on 2026-05-25 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_cargo_superior'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='accounts.departamento'),
        ),
    ]
